# string constant to identify hdf5 datasource
HDF5_DATA_SOURCE = "vtools.datastore.hdf5.HDF5Service"


## HDF_TS_CLASS
HDF_TS_CLASS="TIMESERIES"

## HDF_DIMENSION_SCALE_CLASS
HDF_DIMENSION_SCALE_CLASS="DIMENSION_SCALE"

## HDF TIME SCALE DIMENSION
HDF_TIME_SCALE="time"